### ISSUE TITLE
Not working with latest code version

### ISSUE THREAD

**Issue by mteichtahl** [chenxsan/vscode-standard-format#1]
having upgraded to Version 0.10.10 (0.10.10), this extension no longer works

**Comment by chenxsan** [comment]
@mteichtahl Just published a new version to extension market, please upgrade this extension.

Should use the new `Format code with standard-format` command now until I figure out what's wrong with the `Format Code` function.

**Comment by sebastiankr** [comment]
using  vscode: 0.10.11, vscode-standard-format: 0.0.8 on Mac

right-click `Format Code` still does NOT work. 
`Format code with standard-format` does work

suggest re-opening this issue

**Comment by mteichtahl** [comment]
+1

**Comment by akonoupakis** [comment]
I also think you should reopen this issue.

I am on windows 10, with vscode 0.10.11,
Format Code works but not as expected by standardJs,
and the Format code with standard-format breaks with error:
Running the contributed command:'format.standard' failed.

anyone bumping to the same issue, any suggestions on previous vscode versions? I tried a few but could not get it to work

**Comment by chenxsan** [comment]
I'll keep this issue open until it's fixed.

I filed an issue on https://github.com/Microsoft/vscode/issues/4058 about `Format Code` problem, seems like a bug there.

@akonoupakis Standard-format doesn't support some es6/es7 feathers for the time being, `async`/`await` for example, they would break standard-format. Make sure you are not trying to format them. You can workaround these problems by formatting only those selected code with `Format code with standard-format` command.

**Comment by chenxsan** [comment]
I think it's fixed in VSCode 1.3.0.
