### ISSUE TITLE
error when formatting es6 arrow functions 

### ISSUE THREAD

**Issue by DeanKamali** [chenxsan/vscode-standard-format#10]
I get an error when writing es6 arrow functions 

```
 componentDidUpdate = () =>  {
}
```

<img width="492" alt="screen shot 2018-03-16 at 10 46 15 pm" src="https://user-images.githubusercontent.com/1252959/37550881-f9e8676e-296b-11e8-9b2e-6dfbea7af71a.png">

**Comment by chenxsan** [comment]
This extension is deprecated, please consider use [vscode-standardjs](https://marketplace.visualstudio.com/items?itemName=chenxsan.vscode-standardjs) instead.
