### ISSUE TITLE
Getting error `Running the contributed command:'format.standard' failed.`

### ISSUE THREAD

**Issue by ccutch** [chenxsan/vscode-standard-format#4]
When trying to run `Format code with standard-format` I am getting this error. Help pls

**Comment by chenxsan** [comment]
There are some new features in ES6/ES7 not supported by standard-format, for example,`async/await`, when you try to format these with standard-format, it will fail.

Please use [vscode-standardjs](https://marketplace.visualstudio.com/items?itemName=chenxsan.vscode-standardjs) to lint your files, if any report around new features, you'd better select those code won't break standard-format, and run `Format code with standard-format`, or just use the shortcut ⌘⌥f.

It's kind of a workaround, but until standard-format support all the features, we have no other better way :).

**Comment by ccutch** [comment]
Awesome thank you for the response. Should I close issue?

**Comment by chenxsan** [comment]
😄 yes, please.

On Friday, 20 May 2016, Connor McCutcheon notifications@github.com wrote:

> Awesome thank you for the response. Should I close issue?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/chenxsan/vscode-standard-format/issues/4#issuecomment-220513804

## 

Sam Chen

Blog - https://www.zfanw.com/blog/
