### ISSUE TITLE
Is it possible to format on save?

### ISSUE THREAD

**Issue by davidpellerin** [chenxsan/vscode-standard-format#5]
After looking through the [Visual Studio Code Docs](https://code.visualstudio.com/docs/customization/keybindings), I can't seem to see a way that I can configure my keyboard bindings so that Standard formatting happens _before_ the file is saved.  It would be ideal if I could use the standard Cmd+S / Ctrl-S key binding and have it apply to the current file (if it is a Javascript file)

**Comment by chenxsan** [comment]
@davidpellerin Pushed a commit here https://github.com/chenxsan/vscode-standard-format/commit/29da7dcf0ab8a74f6f11cc03149ba504ea1ab9e1.

So after update to 0.0.9, just add some configurations to your VSCode user setting file `settings.json`

```
"standardFormat": {
  "formatOnSave": true
}
```

It should work then.

**Comment by davidpellerin** [comment]
@chenxsan Thank you!  This is awesome!

**Comment by davidpellerin** [comment]
@chenxsan Tested it out.  Works like a charm.
