### ISSUE TITLE
Error with the new version of VSCode

### ISSUE THREAD

**Issue by wcastand** [chenxsan/vscode-standard-format#9]
VSCode: Version 1.6.0 (1.6.0)
Osx: macOS Sierra

On the new version of VSCode we get the Error: 
`Error: Path must be a string. Received undefined`

**Comment by chenxsan** [comment]
I'm running VSCode 1.6.0 on macOS Sierra too, not having this problem. Will reinstalling the extension help you?

Btw, standard-format might get deprecated later, I would suggest using [vscode-standardjs](https://github.com/chenxsan/vscode-standardjs) in the future, it's based on vscode-eslint with formatting built in.

**Comment by wcastand** [comment]
I try to reinstall and it seems to work.
Thank Bor the update I'll use the new package now.
